services:
    bot:
        image: "ghcr.io/hackerembassy/hackerembassy-tg-bot:local"
        build:
            context: "."
            dockerfile: ./deploy/Containerfile
        volumes:
            - config:/app/config/sec
            - db:/app/data/db
            - logs:/app/log
        environment:
            - NODE_ENV=production
            - BOTDEBUG=true
            - HACKERBOTTOKEN=$HACKERBOTTOKEN
            - UNLOCKKEY=$UNLOCKKEY
            - HACKERGOOGLEAPIKEY=$HACKERGOOGLEAPIKEY
            - OPENAIAPIKEY=$OPENAIAPIKEY
            - WIKIAPIKEY=$WIKIAPIKEY
            - OUTLINE_SIGNING_SECRET=$OUTLINE_SIGNING_SECRET
        ports:
            - "3000:3000"
volumes:
    config:
        name: "hackerembassy-tg-config"
    db:
        name: "hackerembassy-tg-bot-db"
    logs:
        name: "hackerembassy-tg-bot-logs"
